# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # dependabot does not support pnpm yet.
  # Track the issue: https://github.com/dependabot/dependabot-core/issues/1736
