name: Test

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - name: Cache Turborepo Tasks
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-turbo-
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm cov
